`timescale 1ns/1ps 

//////////////////////////////////////////////////////////////////////
//This testbench was automatically generated by 
//the TestBenchWriter class of VerilogWriter
//////////////////////////////////////////////////////////////////////

module test; 

	//inputs
	reg auto_clock;
	reg A;
	reg B;

	//expected results
	reg YExpected;

	//outputs
	wire Y;
	integer error, ch;


	reg[31:0] vectornum, errors;

	reg[2:0] testvectors[10000:0];

	//Instantiate the Unit Under Test (UUT)
	New_Project uut(
		.auto_clock(auto_clock),
		.A(A),
		.B(B),
		.Y(Y)
	);

	always
		begin
			Pins.Pin=1; #5; Pins.Pin=0; #5;
		end

	initial
		begin
			error = $fopen("error.log");
			if(error==0) $stop(2);
			ch = error|1;
			$readmemb("testVect.tv", testvectors);
			vectornum=0; errors=0;
		end

	always @ (posedge Pins.Pin)
		begin
			#1; {A, B, YExpected}=
			testvectors[vectornum];
		end

	always @ (negedge auto_clock)
		begin
			if (Y!==YExpected)begin
				$display("Error:");
				$fdisplay(ch, "A=%b", A);
				$fdisplay(ch, "B=%b", B);
				$fdisplay(ch, "Expected: Y=%b (%b expected)",
						Y, YExpected);
				errors = errors + 1;
			end

			vectornum=vectornum + 1;
			if( testvectors[vectornum]===3'bx)begin
				$display("%d tests completed with %d errors",
						vectornum, errors);
				$fclose(error);
				$finish;
			end
		end

endmodule