#This scrip file was automatically
#Generated by uiWorkPath.dll

project new lab1_xx.ise

project set family spartan3
project set device xc3s400
project set package tq144
project set speed -4
project set top_level_module_type schematic
project set generated_simulation_language "Modelsim-SE Verilog"
project close