`timescale 1ns/1ps 

//////////////////////////////////////////////////////////////////////
//This testbench was automatically generated by 
//the TestBenchWriter class of VerilogWriter
//////////////////////////////////////////////////////////////////////

module test; 

 //inputs
  reg clk;
  reg [3:0] s;

    //expected results
  reg [7:0] ledExpected;

    //outputs
  wire [7:0] led;
integer error, ch;


    reg[31:0] vectornum, errors;

    reg[11:0] testvectors[10000:0];

    //Instantiate the Unit Under Test (UUT)
   led uut(
      .clk(clk),
      .s(s),
      .led(led)
  );

  always
    begin
         clk=1; #5; clk=0; #5;
       end

  initial
     begin
           error = $fopen("error.log");
           if(error==0) $stop(2);
           ch = error|1;
           $readmemb("testVect.tv", testvectors);
           vectornum=0; errors=0;
        end

    always @ (posedge clk)
        begin
           #1; {s[3:0], ledExpected[7:0]}=
          testvectors[vectornum];
       end

    always @ (negedge clk)
        begin
      if(led[7:0] !==ledExpected[7:0])begin
          $display("Error:");
          $fdisplay(ch, "s=%b", s);
          $fdisplay(ch, "outputs=%b (%b expected)",
                       led, ledExpected);
          errors = errors + 1;
      end

      vectornum=vectornum + 1;
      if(testvectors[vectornum]===12'bx)begin
           $display("%d tests completed with %d errors",
                       vectornum, errors);
           $fclose(error);
           $finish;
      end
   end

endmodule