using System;
using System.IO;
using System.Collections.Generic;
using System.Drawing;
using System.Windows.Forms;
using Pins;

namespace VerilogWriter
{
	/// <summary>
	///	this class is used only in the printmodule() function to print
	/// the first line in Verilog which declares the new module
	/// and its inputs and outputs, and the last line in the module which
	/// is always "endmodule"
	/// </summary>
    class ModuleStruct
	{
        //internal variables
		List<Pin> alloutputs;
		List<Pin> allinputs;
		String modulename;
		List<Pin> wirelist;
		
        /// <summary>
        /// Constructor for ModuleStruct class
        /// </summary>
        /// <param name="modulename">String containing module name</param>
        /// <param name="alloutputs">List of output pins</param>
        /// <param name="allinputs">List of input pins</param>
        /// <param name="wirelist">List of wire pins</param>
        public ModuleStruct(string modulename,List<Pin> alloutputs, List<Pin> allinputs, List<Pin> wirelist)
		{
			this.modulename = modulename;
			this.alloutputs = new List<Pin>(alloutputs);
			this.allinputs = new List<Pin>(allinputs);
			this.wirelist = new List<Pin>(wirelist);
		}

		/// <summary>
		/// Prints the header and instantiation code for the verilog module
		/// </summary>
		/// <param name="filepath">String containing desired file directory path</param>
		/// <param name="filename">String containing desired file name</param>
		/// <returns>Boolean indicating whether print succeeded</returns>
		public Boolean printNewModule(String filepath, String filename)
		{
            //If there are either no inputs or outputs, return false
            if (allinputs.Count == 0 || alloutputs.Count == 0)
                return false;

            //Set up file writer
            FileStream inputfile = new FileStream(filename + ".v", FileMode.Create, FileAccess.Write);
            StreamWriter sWriter = new StreamWriter(inputfile);

            //The header of the verilog file
            String header =
                "//////////////////////////////////////////////////////////////////////\n" +
                "//This testbench was automatically generated by \n" +
                "//the TestBenchWriter class of VerilogWriter\n" +
                "//////////////////////////////////////////////////////////////////////\n\n";

            sWriter.Write(header);

            //instantiate the module
			sWriter.Write("module {0}(",modulename);
			
            //write out the inputs
            foreach(Pin datain in allinputs)
			{
				sWriter.Write("input[");
				sWriter.Write(datain.bussize-1);
				sWriter.Write(":0] {0}, ",datain.PinName);
			}

            //write out the outputs
			foreach(Pin dataout in alloutputs)
			{
                //if its the first pin in the list
				if(dataout.Equals(alloutputs[0]))
				{
					sWriter.Write("output[");
					sWriter.Write(dataout.bussize-1);
					sWriter.Write(":0] ");
					sWriter.Write(dataout.PinName);
				}

                //otherwise
				else
				{
					sWriter.Write(", output[");
					sWriter.Write(dataout.bussize-1);
					sWriter.Write(":0] " + dataout);
				}
			}

            //close the module instiation
			sWriter.WriteLine(");");

            //close the file
			sWriter.Close();

            //write succeeded
            return true;
		}//end printnewmodule

		/// <summary>
		/// Adds list of wires to top of module
		/// </summary>
        /// <param name="filepath">String containing desired file directory path</param>
        /// <param name="filename">String containing desired file name</param>
		public void printwires(String filepath,String filename)
		{
            //Set up filewriter
            FileStream inputfile = new FileStream(filename + ".v", FileMode.Append, FileAccess.Write);
            StreamWriter sWriter = new StreamWriter(inputfile);

			sWriter.WriteLine();//Blank line for spacing
			
            //Go through each pin in the list of wires and print it to the file
            foreach(Pin s in wirelist)
			{
				sWriter.WriteLine("wire[{0}:0] {1};",s.bussize-1,s.PinName);
			}
			sWriter.WriteLine();//Blank line for spacing

            //close the streamWriter
			sWriter.Close();
		}//end printwires

		/// <summary>
		/// Prints the last line of the module
		/// </summary>
        /// <param name="filepath">String containing desired file directory path</param>
        /// <param name="filename">String containing desired file name</param>
        public void printend(String filepath, String filename)
		{
            //set up the streamWriter
            FileStream inputfile = new FileStream(filename + ".v", FileMode.Append, FileAccess.Write);
            StreamWriter sWriter = new StreamWriter(inputfile);

            //write the end of the module
			sWriter.WriteLine("endmodule");

            //close the stream writer
			sWriter.Close();
		}
	}//end class modulestruct

}

